### ISSUE TITLE
New account process incorrectly populates `codeowners` file

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7430] opened 2024-07-05 10:25 UTC
### Expected Behavior

From our guidance on [creating new accounts for customers](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-environments.html#blank-example) the `codeowners` key has a value of `[""]` which should result in the previous behaviour before this field was introduced being followed. EG. For every `github-team` in the application environments, these teams should be represented in the `CODEOWNERS` file.

### Actual Behavior

When we set `codeowners: [""]` as defined in our example, instead of ignoring this field the CODEOWNERS file is populated like so:
```
/terraform/environments/$example-application @ministryofjustice/ @ministryofjustice/modernisation-platform
```

### Steps to Reproduce the Problem

See this application json: https://github.com/ministryofjustice/modernisation-platform/blob/54474cf47a198b0029882e23cc55a69d37e99727/environments/genesys-call-centre-data.json
And this version of the `modernisation-platform-environments` CODEOWNERS file: https://github.com/ministryofjustice/modernisation-platform-environments/blob/aebfcdb8b292819d415988d3b1e239dd375ffd6d/.github/CODEOWNERS

The relevant script should be this: https://github.com/ministryofjustice/modernisation-platform/blob/36e3d9185ae2bfd39c17c94f337e40b7ccfae0cf/scripts/provision-member-directories.sh#L138

**Comment by SteveLinden** [comment] 2024-07-09 10:28
I've had a quick look at the code and it looks like this may be the issue. If there's no codeowners it looks like it defaults to the modernisation-platform ID.
    
if [ -n "$codeowners" ]; then
        echo "Adding $directory $codeowners@ministryofjustice/modernisation-platform  to codeowners"
        echo "$directory $codeowners@ministryofjustice/modernisation-platform" >> $codeowners_file
      # otherwise, use the github_slugs array
      else
        echo "Adding $directory $github_slugs@ministryofjustice/modernisation-platform to codeowners"
        echo "$directory $github_slugs@ministryofjustice/modernisation-platform" >> $codeowners_file
      fi

Going to seek clarification on the channel.

**Comment by SteveLinden** [comment] 2024-07-10 08:56
Based on my chatgpt information I can find the missing codeowners using this code
# Read the CODEOWNERS file, filter out comments and empty lines
codeowners_entries=$(grep -v -e '^#' -e '^$' ${codeowners_file})

# Find entries with missing or blank owners
missing_codeowners=$(echo "${codeowners_entries}" | awk '$2 == "" {print $1}')

awk '$2 == "" {print $1}' identifies entries where the owner field is empty.
These entries are printed as paths with missing code owners.

All of the above may be helpful but will need to be tested.

**Comment by SteveLinden** [comment] 2024-07-10 14:30
Raised a PR but the team aren't willing to approve. I will remove it and see if I can correct with another change - Ewa has suggested "Instead why don’t you flip the logic (don’t check if the string is populated, but check if the string is empty or unset)? " but I have a feeling the code "if [ -n "$codeowners" ]; then" already does that, sort of.

**Comment by SteveLinden** [comment] 2024-07-11 15:43
I put a PR up with proposed changes #7496 

After chatting to person who raised it I found it was only in one place so I raised a call to amend the documentation #7500

**Comment by richgreen-moj** [comment] 2024-07-12 16:54
@SteveLinden - I've had a look today and added a comment to the PR. I'll repeat it here though...

When I tried running https://github.com/ministryofjustice/modernisation-platform/pull/7496 locally it made more changes to the CODEOWNERS file than expected. In my view the ideal scenario is that we update the script and re-run it so that the only change it would make is to the error on the [/terraform/environments/genesys-call-centre-data](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.github/CODEOWNERS#L34) line.

I've found a more succinct way of altering the if statement [here](https://github.com/ministryofjustice/modernisation-platform/blob/907928fbfea35b2ca884f25c0f9c7064f7164912/scripts/provision-member-directories.sh#L157)
`if [ -n "$codeowners" ] && [ "$codeowners" != "@ministryofjustice/ " ]; then`

I found that on this [line](https://github.com/ministryofjustice/modernisation-platform/blob/907928fbfea35b2ca884f25c0f9c7064f7164912/scripts/provision-member-directories.sh#L152) where `$codeowners` is defined, the JQ is appending `@ministryofjustice/` to any values in `.codeowners[]` which means that rather than `$codeowners` being a null value it is actually given a value of `@ministryofjustice/` and so the logic was adding that to the file.

I tested it locally and it worked as expected. I can show you that and help you to try running it locally.

**Comment by richgreen-moj** [comment] 2024-07-15 08:37
I just tried this suggestion from @ASTRobinson https://mojdt.slack.com/archives/C013RM6MFFW/p1720713676525369?thread_ts=1720710968.252469&cid=C013RM6MFFW
`codeowners=$(jq -r 'try (.codeowners[] | select(length > 0) | "@ministryofjustice/" + .)' ${environment_json_dir}/${application_name}.json | sort | uniq | tr '\n' ' ')`
It's better than my suggestion above as it sorts the issue at it's root cause e.g. doesn't populate the value of `codeowners` with a spurious value and saves having to alter the logic in the if statement.

**Comment by SteveLinden** [comment] 2024-07-16 14:48
After discussing with Rich this will only update one record - the one with the issue. 

Based on this it appears to amended code will work correctly.

I have updated the PR (above) with the amended code.

**Comment by SteveLinden** [comment] 2024-07-17 10:31
Made the change listed above and the PR was successfully merged. 
Now I will amend the documentation to make it clearer what should be used. It will not cause an impact if the "codeowners": [""], is used

**Closed** 2024-07-17 10:31 UTC
Labels: bug, new environment automation
