### ISSUE TITLE
PPUD AWS Shield enablement

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#3538] opened 2023-03-29 11:55 UTC
## User Story

As a devops user we have been requested to enable AWS shield on the PPUD development account to add extra protection against DDos attacks.

Needs to be completed before their IT health check on the 26th April.

### Proposal
The proposal is to do the change in development first and for end users to test for any adverse behaviour. 

## Definition of done

- [x] Code created for monitoring
- [x] smt settings enabled in aws shield in development
- [x] Enable Automatic Layer 7 Mitigation
- [x] tests are green
- [x] feedback from user

**Comment by SimonPPledger** [comment] 2023-04-13 10:33
@markgov we thought this was already the case, can you confirm

**Comment by SteveLinden** [comment] 2023-04-20 13:31
Looking at the code in monitoring.tf from sprinkler. Looks like this can be used with a few minor adjustments.

**Comment by SteveLinden** [comment] 2023-04-21 13:15
The PR was approved by the modernisation-platform team and then the user ran the apply on development as we don't have access to do this.

This was successful. User may want the changes doing on preproduction and production so that it is in place when needed. Just awaiting confirmation.
PR - https://github.com/ministryofjustice/modernisation-platform-environments/pull/2016

**Comment by SteveLinden** [comment] 2023-04-21 14:41
Implemented the manual changes for preproduction and production.

**Comment by SteveLinden** [comment] 2023-04-21 14:50
Moving this to done but we will have to check the settings on the count in a couple of weeks and set it to block. This is based on the comment in the instructions
_**"Once the configuration is complete, monitor the WAF metrics and Shield events for 1-2 weeks to ensure that there are no false positives with the new rules. Then return to the configuration, and change the “Count” to “Block” for the rate limit rule and for the automatic mitigation."**_

**Comment by SteveLinden** [comment] 2023-04-24 09:58
There were issues on the production shield so I reopened this call. The ones they wanted to change were actually set as elastic IP which cannot be set using the details we have in place. I am, therefore, closing the call as we have done what was needed

**Closed by SteveLinden** 2023-04-24 09:58 UTC
