### ISSUE TITLE
Terraform Static Analysis pipeline failing in tflint v0.50.0

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#5899] opened 2024-01-03 10:05 UTC
### Expected Behavior

Terraform Static Analysis pipeline in all repositories should run clean of the following error:
```
Error: Invalid index

  on terraform/environments/planetfm/locals.tf line 11, in locals:
  11:   baseline_environment_config = local.environment_configs[local.environment]

with local.environment as "default",
     local.environment_configs as object with 4 attributes.

The given key does not identify an element in this collection value.
```

### Actual Behavior

The [pipelines](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/7394393505/job/20115700112) fails with errors looking like the one below:
```
Error: Invalid index

  on terraform/environments/planetfm/locals.tf line 11, in locals:
  11:   baseline_environment_config = local.environment_configs[local.environment]

with local.environment as "default",
     local.environment_configs as object with 4 attributes.

The given key does not identify an element in this collection value.
```

**NOTE**, this is just an example of one pipeline, but the issue will exist in all repositories/pipelines where the code relies on the `terraform.workspace` variable. This is because the newest version of the tflint (v.0.50.0) had breaking changes, specifically, the scanning of local modules is enabled by default, which in the case of the platform code fails, as in some places the code relies on the `terraform.workspace` variable (e.g. when retrieving keys for environments), which includes default workspace, which the platform does not use. 

### Steps to Reproduce the Problem

Run `Terraform Static Analysis` pipeline. NOTE, it is already fixed in the `modernisation-platform` repo.

The fix will be to bump github-actions to use the latest version, where the new feature is that allows you to pass a setting to the tflint. The fix will still run a full scan, but it will skip the local module scanning, as it used to in the tflint v0.49.0 (and which is now enabled by default in tflint v0.50.0). See the fix here and apply it to the failing pipelines in all MP repositories: https://github.com/ministryofjustice/modernisation-platform/issues/5890 

### Version

tflint 0.50.0

**Comment by mikereiddigital** [comment] 2024-01-11 15:38
@dms1981 kindly updated the terraform-static-analysis github action to v15.2.0 (https://github.com/ministryofjustice/github-actions) and first PR was to update it in Modernisation Platform and test it there. 

PR - https://github.com/ministryofjustice/modernisation-platform/pull/5953

Once that has had a successful run I will prepare a PR for Modernisation Platform Environments and check & confirm which other repos require it updating.

**Comment by mikereiddigital** [comment] 2024-01-12 09:15
All three jobs in the action have run successfully since yesterday in Modernisation Platform so will apply to Mod Platform Envs.

**Comment by mikereiddigital** [comment] 2024-01-12 10:34
PR https://github.com/ministryofjustice/modernisation-platform-environments/pull/4519 applied to the environments repo. Will trigger a test run & then monitor for the occurrence of the original error. Also checking for other MP repos where this action is used.

**Comment by mikereiddigital** [comment] 2024-01-12 14:21
Following Modernisation Platform Repos also reference this action:

- [ministryofjustice/modernisation-platform-ami-builds](https://github.com/ministryofjustice/modernisation-platform-ami-builds)

- [ministryofjustice/modernisation-platform-terraform-bastion-linux](https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux)

- [ministryofjustice/modernisation-platform-terraform-cross-account-access](https://github.com/ministryofjustice/modernisation-platform-terraform-cross-account-access)

- [ministryofjustice/modernisation-platform-terraform-ecs-cluster](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster)

- [ministryofjustice/modernisation-platform-terraform-ssm-patching](https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching)

- [ministryofjustice/modernisation-platform-terraform-trusted-advisor](https://github.com/ministryofjustice/modernisation-platform-terraform-trusted-advisor)

These will all have PRs prepared when it's confirmed on Monday morning that the 7am scheduled run has completed.

**Comment by mikereiddigital** [comment] 2024-01-15 08:56
Job is showing an error but the errors themselves are valid exceptions based on the rules used. For example:

Check: CKV_AWS_158: "Ensure that CloudWatch Log Group is encrypted by KMS"
	FAILED for resource: module.glue_reporting_hub_batch_job.aws_cloudwatch_log_group.sec_config_error
	File: /modules/glue_job/main.tf:203-207
	Calling File: /main.tf:79-128
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-that-cloudwatch-log-group-is-encrypted-by-kms

		203 | resource "aws_cloudwatch_log_group" "sec_config_error" {
		204 |   name              = "/aws-glue/jobs/${var.short_name}-sec-config-role/${var.name}-glue-role/error"
		205 |   retention_in_days = var.log_group_retention_in_days
		206 |   tags              = var.tags
		207 | }

Check: CKV_AWS_338: "Ensure CloudWatch log groups retains logs for at least 1 year"
	FAILED for resource: module.glue_reporting_hub_batch_job.aws_cloudwatch_log_group.sec_config_error
	File: /modules/glue_job/main.tf:203-207
	Calling File: /main.tf:79-128

		203 | resource "aws_cloudwatch_log_group" "sec_config_error" {
		204 |   name              = "/aws-glue/jobs/${var.short_name}-sec-config-role/${var.name}-glue-role/error"
		205 |   retention_in_days = var.log_group_retention_in_days
		206 |   tags              = var.tags
		207 | }

I will speak with @ewastempel later today & confirm whether we want these as exceptions to be ignored or not.

**Comment by mikereiddigital** [comment] 2024-01-15 16:23
Catch up with @ewastempel. Fix already applied to modernsation-platform-environments. Adding to:

https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/669 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/339 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-cross-account-access/pull/254 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster/pull/80 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching/pull/299 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-trusted-advisor/pull/214 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/pull/287 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/pull/350 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/366 (merged)

https://github.com/ministryofjustice/modernisation-platform-terraform-ecs/pull/127 (merged)

All of the above PRs have been approved & merged.

**Comment by mikereiddigital** [comment] 2024-01-16 09:32
Moving to done.

**Closed** 2024-01-17 08:52 UTC
Labels: bug
