### ISSUE TITLE
🧪 Add unit tests where missing

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6490] opened 2024-03-14 14:02 UTC
### User Story

As a Modernisation Platform Engineer
I want to add unit tests to modules where they are missing
So that I increase confidence in these modules

here is an example of tests - https://github.com/ministryofjustice/modernisation-platform-terraform-pagerduty-integration/tree/main/test

### Value / Purpose

All of our modules should have unit tests. We note this in our [User Guide](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/sdlc/testing-strategy.html). As part of a [recent spike](https://github.com/ministryofjustice/modernisation-platform/issues/6334) some gaps in our test coverage were noted, so this story should cover adding basic unit test functionality.

### Useful Contacts

@dms1981

### Additional Information

The following repositories were seen to lack unit tests:

- [x] modernisation-platform-ami-builds
- [x] modernisation-platform-configuration-management
- [x] modernisation-platform-cp-network-test
- [x] modernisation-platform-incident-response - (repository has been archived)
- [x] modernisation-platform-terraform-baselines
- [x] modernisation-platform-terraform-cross-account-access
- [x] modernisation-platform-terraform-dns-certificate
- [x] modernisation-platform-terraform-iam-superadmins
- [x] modernisation-platform-infrastructure-test  - (repository has been archived)
- [x] modernisation-platform-terraform-member-vpc

### Definition of Done

- [x] Missing unit tests added
- [x] New unit tests pass
- [x] Another team member has reviewed
- [x]  New tickets raised for any more complicated tests required

**Comment by ASTRobinson** [comment] 2024-05-03 16:05
modernisation-platform-terraform-member-vpc - branch created, vpc successfully created but failing to destroy due to permissions: https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/pull/374

**Comment by ASTRobinson** [comment] 2024-05-03 16:32
modernisation-platform-terraform-iam-superadmins - branch created, terraform working but test failing due to permission error: https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins/pull/362

**Comment by ASTRobinson** [comment] 2024-05-07 14:46
modernisation-platform-ami-builds - todo
modernisation-platform-configuration-management - todo (Ansible / PowerShell testing) no terraform.
modernisation-platform-cp-network-test - todo (Docker / Kubernetes testing) no terraform.

modernisation-platform-terraform-baselines - @SteveLinden looking at 👀 
modernisation-platform-terraform-cross-account-access - working on now
modernisation-platform-terraform-iam-superadmins - started [362](https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins/pull/362)
modernisation-platform-terraform-member-vpc - started [374](https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/pull/374)

Not Required: 
modernisation-platform-terraform-dns-certificate (ignore for now as it is not in use)
modernisation-platform-infrastructure-test - (repository has been archived)
modernisation-platform-incident-response - (repository has been archived)

**Comment by SteveLinden** [comment] 2024-05-24 15:42
Got the modernisation-platform-terraform-baselines back correctly but still issues on modernisation-platform plan. Different to previous ones so may need to look at them individually.

**Comment by SteveLinden** [comment] 2024-05-28 13:21
Getting errors when using the baselines/secure_baseline option. OK when running against sprinkler. 
I have, therefore, decided to leave this as it is for the time being while I go onto a couple of other calls and 10% time.

Will look again on Aaron's return if this remains in its current state.
"baselines/secure-baseline gives me an error on
enable_cloudtrail_s3_mgmt_events = local.enable-cloudtrail-events
and
enabled_imdsv2_regions = local.enabled_baseline_regions
Both exist in locals so I’m not sure what the issue is. "

**Comment by SteveLinden** [comment] 2024-06-17 10:13
The branch I have on the baselines is feature/baselines-changes-6490 for anyone to look at

**Comment by richgreen-moj** [comment] 2024-06-21 14:47
I've raised a PR for adding unit tests for the backup module within the baselines module https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/492.

**Comment by richgreen-moj** [comment] 2024-06-21 14:56
The baseline module has the following child modules:

- access-analyzer :x: (Not testable - only 1 resource allowed per region and not adjustable limit)
- backup
- cloudtrail
- config
- ebs
- guardduty :x: (Not testable - only 1 resource allowed per region and not adjustable limit)
- iam
- imdsv2
- securityhub
- securityhub-alarms
- support

**Comment by ASTRobinson** [comment] 2024-06-24 16:27
I am closing this ticket as either unit-tests have been successfully created, not required or follow-on tickets have been raised.

**Closed by ASTRobinson** 2024-06-24 16:27 UTC
Labels: testing
