### ISSUE TITLE
Remove old public snapshots from modernisation platform

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#3868] opened 2023-05-15 14:30 UTC
When doing some KMS experiments I noticed snapshots going back to 2016. We probably need to tidy these up to save some money and make things a little neater.

## Environment details
All environments

## Other information

This is primarily to tidy up the system and remove public snapshots that are around 7 years old. The removal will not include individual application snapshots only those defined as public.

## Definition of done
We need to determine "n" specified below

- [ ] public snapshots only n years old
- [ ] costs before the removal and after the removal calculated

**Comment by davidkelliott** [comment] 2023-05-19 15:34
@SteveLinden which accounts were these in?  When you say public are the snapshots owned by us and have been made public?

**Comment by SimonPPledger** [comment] 2023-06-22 10:23
closed as a duplicate of #4122

**Closed** 2023-06-22 10:23 UTC
Labels: needs refining, billing, support
